In [1]:
import numpy as np
np.set_printoptions(threshold=np.inf, linewidth=300)

In [2]:
P = np.array([[0.24376259, 0.        , 0.        , 0.        , 0.28668836, 0.        , 0.        , 0.        , 0.        , 0.08213234, 0.        , 0.38741671, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.28414097, 0.        , 0.        , 0.        , 0.        , 0.        , 0.29735683, 0.        , 0.        , 0.        , 0.        , 0.        , 0.4185022 , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.0771028 , 0.        , 0.        , 0.49065421, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.43224299, 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.30172414, 0.        , 0.        , 0.1637931 , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.53448276, 0.        , 0.        ],
       [0.14905714, 0.        , 0.        , 0.        , 0.1753056 , 0.        , 0.        , 0.12792571, 0.        , 0.05022269, 0.        , 0.23689946, 0.        , 0.18004359, 0.        , 0.        , 0.        , 0.        , 0.08054582, 0.        ],
       [0.        , 0.        , 0.06432749, 0.        , 0.        , 0.40935673, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.36062378, 0.        , 0.        , 0.        , 0.16569201, 0.        ],
       [0.        , 0.        , 0.        , 0.21084337, 0.        , 0.        , 0.11445783, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.30120482, 0.37349398, 0.        , 0.        ],
       [0.        , 0.20187793, 0.        , 0.        , 0.28951487, 0.        , 0.        , 0.21126761, 0.        , 0.        , 0.        , 0.        , 0.        , 0.29733959, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.24626866, 0.        , 0.46268657, 0.        , 0.        , 0.        , 0.        , 0.29104478, 0.        , 0.        , 0.        , 0.        ],
       [0.39792563, 0.        , 0.        , 0.        , 0.46799899, 0.        , 0.        , 0.        , 0.        , 0.13407539, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.1875    , 0.        , 0.35227273, 0.        , 0.14204545, 0.        , 0.        , 0.22159091, 0.        , 0.        , 0.09659091, 0.        ],
       [0.16963227, 0.        , 0.        , 0.        , 0.19950394, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.26959991, 0.        , 0.        , 0.        , 0.        , 0.26959991, 0.        , 0.09166397, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.20327869, 0.        , 0.08196721, 0.        , 0.12131148, 0.        , 0.        , 0.        , 0.0557377 , 0.53770492],
       [0.        , 0.1781768 , 0.        , 0.        , 0.25552486, 0.        , 0.        , 0.18646409, 0.        , 0.        , 0.        , 0.        , 0.        , 0.26243094, 0.        , 0.        , 0.        , 0.        , 0.11740331, 0.        ],
       [0.        , 0.        , 0.02263374, 0.        , 0.        , 0.14403292, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.08573388, 0.        , 0.12688615, 0.        , 0.        , 0.        , 0.05829904, 0.56241427],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.1641791 , 0.        , 0.30845771, 0.        , 0.        , 0.        , 0.        , 0.19402985, 0.24875622, 0.        , 0.08457711, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.08016878, 0.        , 0.        , 0.        , 0.        , 0.21097046, 0.        , 0.        , 0.        , 0.16455696, 0.21097046, 0.26160338, 0.07172996, 0.        ],
       [0.        , 0.        , 0.        , 0.21084337, 0.        , 0.        , 0.11445783, 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.30120482, 0.37349398, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.09319899, 0.10579345, 0.        , 0.        , 0.        , 0.        , 0.15617128, 0.12594458, 0.06297229, 0.09571788, 0.09319899, 0.09823678, 0.12594458, 0.        , 0.04282116, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.11061947, 0.        , 0.16371681, 0.        , 0.        , 0.        , 0.        , 0.72566372]])

tiempos = np.array([[  0.   , 143.969, 353.368, 110.582,  17.775,  95.005,  95.187,  88.743,  77.792, 202.774,  43.36 ,   9.136,  56.441,  60.097,  60.175,  40.352,  24.646,  61.563,  21.076,  60.82 ],
       [ 60.301,   0.   , 353.848, 120.052,  15.305,  95.288, 104.657,  32.114,  81.234, 229.15 ,  46.079,  25.874,  57.617,  10.033,  60.878,  44.943,  34.117,  71.034,  20.369,  61.713],
       [106.917, 191.065,   0.   , 139.552,  75.164,  27.095, 124.158, 138.819,  79.832, 282.923,  40.94 ,  61.172,  23.95 , 105.074,   8.926,  49.481,  53.617,  90.534,  27.729,  17.134],
       [ 82.4  , 175.538, 357.822,   0.   ,  55.462,  99.968,  38.54 , 122.083,  74.554, 261.008,  41.998,  32.54 ,  59.088,  90.407,  64.049,  34.131,   5.755,   4.917,  28.609,  64.199],
       [ 48.206, 129.404, 352.047, 114.075,   0.   ,  93.578,  98.68 ,  73.249,  78.056, 215.319,  43.237,  16.521,  55.492,  46.192,  58.973,  41.232,  28.139,  65.056,  19.119,  59.719],
       [103.044, 186.995, 281.585, 136.189,  71.186,   0.   , 120.794, 134.776,  78.109, 278.993,  39.618,  57.388,  26.888, 100.986,  14.75 ,  47.122,  50.254,  87.171,  23.3  ,  21.795],
       [ 80.967, 174.106, 356.389,  52.503,  54.029,  98.536,   0.   , 120.651,  73.122, 259.576,  40.566,  31.107,  57.656,  88.975,  62.617,  32.699,   4.322,  14.857,  27.177,  62.767],
       [ 57.089,  84.128, 353.616, 118.611,  11.164,  95.082, 103.216,   0.   ,  80.603, 225.435,  45.546,  23.455,  57.291,  20.791,  60.616,  44.158,  32.676,  69.593,  20.297,  61.425],
       [ 94.076, 181.186, 342.568, 119.021,  63.91 ,  86.355, 103.626, 128.542,   0.   , 270.94 ,   8.054,  46.975,  38.029,  95.479,  46.933,  13.827,  33.085,  70.002,  23.256,  45.493],
       [ 27.208, 137.252, 353.809, 113.624,   9.323,  95.388,  98.229,  81.524,  79.09 ,   0.   ,  44.448,  14.282,  57.083,  53.736,  60.68 ,  41.982,  27.689,  64.606,  21.173,  61.38 ],
       [ 95.047, 181.434, 339.079, 121.867,  64.493,  83.267, 106.472, 128.887,  43.456, 271.701,   0.   ,  48.276,  33.122,  95.658,  42.989,  20.363,  35.932,  72.849,  22.185,  41.16 ],
       [ 53.185, 153.59 , 351.672, 104.771,  30.139,  93.398,  89.376,  99.159,  74.74 , 233.897,  40.638,   0.   ,  54.426,  69.154,  58.376,  36.774,  18.835,  55.752,  19.922,  58.934],
       [107.073, 191.917, 321.033, 137.903,  75.693,  69.481, 122.508, 139.578,  72.376, 283.281,  32.067,  61.009,   0.   , 105.993,  20.108,  44.28 ,  51.967,  88.884,  29.85 ,  14.15 ],
       [ 60.194,  93.799, 351.623, 118.687,  15.858,  93.045, 103.292,  52.543,  79.292, 229.399,  44.068,  25.202,  55.458,   0.   ,  58.674,  43.111,  32.751,  69.669,  18.031,  59.528],
       [109.   , 193.371, 304.202, 141.057,  77.367,  55.537, 125.662, 141.096,  79.474, 285.071,  40.128,  63.153,  18.301, 107.402,   0.   ,  49.846,  55.121,  92.038,  30.443,   9.53 ],
       [ 89.098, 177.356, 344.678, 111.059,  59.547,  87.829,  95.664, 124.558,  46.288, 266.294,  17.422,  41.471,  42.394,  91.759,  49.766,   0.   ,  25.124,  62.041,  21.522,  48.944],
       [ 76.645, 169.783, 352.067,  85.935,  49.707,  94.214,  70.541, 116.329,  68.799, 255.253,  36.244,  26.785,  53.334,  84.652,  58.294,  28.376,   0.   ,  36.917,  22.855,  58.444],
       [ 80.967, 174.106, 356.389,  52.503,  54.029,  98.536,  48.48 , 120.651,  73.122, 259.576,  40.566,  31.107,  57.656,  88.975,  62.617,  32.699,   4.322,   0.   ,  27.177,  62.767],
       [ 82.539, 165.501, 335.644, 118.255,  50.151,  76.725, 102.86 , 113.415,  68.435, 258.202,  31.961,  37.337,  40.681,  79.397,  43.08 ,  34.24 ,  32.319,  69.237,   0.   ,  44.263],
       [111.869, 196.43 , 314.634, 143.43 ,  80.337,  64.805, 128.035, 144.129,  80.257, 287.994,  40.522,  65.934,  14.567, 110.479,  11.753,  51.247,  57.495,  94.412,  33.849,   0.   ]])

In [4]:
print(np.round(tiempos,1))

[[  0.  144.  353.4 110.6  17.8  95.   95.2  88.7  77.8 202.8  43.4   9.1  56.4  60.1  60.2  40.4  24.6  61.6  21.1  60.8]
 [ 60.3   0.  353.8 120.1  15.3  95.3 104.7  32.1  81.2 229.2  46.1  25.9  57.6  10.   60.9  44.9  34.1  71.   20.4  61.7]
 [106.9 191.1   0.  139.6  75.2  27.1 124.2 138.8  79.8 282.9  40.9  61.2  24.  105.1   8.9  49.5  53.6  90.5  27.7  17.1]
 [ 82.4 175.5 357.8   0.   55.5 100.   38.5 122.1  74.6 261.   42.   32.5  59.1  90.4  64.   34.1   5.8   4.9  28.6  64.2]
 [ 48.2 129.4 352.  114.1   0.   93.6  98.7  73.2  78.1 215.3  43.2  16.5  55.5  46.2  59.   41.2  28.1  65.1  19.1  59.7]
 [103.  187.  281.6 136.2  71.2   0.  120.8 134.8  78.1 279.   39.6  57.4  26.9 101.   14.8  47.1  50.3  87.2  23.3  21.8]
 [ 81.  174.1 356.4  52.5  54.   98.5   0.  120.7  73.1 259.6  40.6  31.1  57.7  89.   62.6  32.7   4.3  14.9  27.2  62.8]
 [ 57.1  84.1 353.6 118.6  11.2  95.1 103.2   0.   80.6 225.4  45.5  23.5  57.3  20.8  60.6  44.2  32.7  69.6  20.3  61.4]
 [ 94.1 181.2 34